### ISSUE TITLE
AccGndL→LVDT_Lの伝達関数がおかしい

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-vis/sensor-correction#2]
SVNにあるたくさんの同じような名前のファイルをやめて、確実に動く正しいモデルをこのリポジトリに置きたい。今後はその正しいモデルたちをGit上で管理していきたい。

今そのために、シンプルなメイン関数をつくってたしかめているところ。

しかし自分がつくったメイン関数、
```
sensor-correction/SuspensionControlModel/script/typeA/main.m
```
を実行して、地面の加速度からLVDTのLまでの伝達関数をプロットして、関口さんのD論と比べてみると、どうやら速度からLVDTまでの伝達関数になっている。

計算結果のほうが傾きは-1次だし位相も90°進んでいるので、速度入力を見ている(下図)
![image](https://user-images.githubusercontent.com/24282734/49980382-91bc1580-ff96-11e8-8728-54c6e8f4c333.png)

## ToDo
- [ ] 奥富さんに、現在正しく動いている.matと.slxのファイルをもらう。
- [ ] .matを作り直す

**Comment by MiyoKouseki** [comment]
Help Okutomi-san

**Comment by MiyoKouseki** [comment]
とりあえずsensor correctionはpr3から始めることにするので、typeAは後回しに。

**Comment by YoshinoriFujii** [comment]
### check with etoal83
- etoal83 model (available from [SVN](https://granite.phys.s.u-tokyo.ac.jp/svn/LCGT/trunk/VIS/SuspensionControlModel/script/TypeA/controlmodel/ "SVN"), slx modelは、SVNに上がったたものと地面付近は少なくとも同じだった) でも同じプロットが得られた。
  - [ IP_LVDT_L / accGND_L ] は低周波側で 1/w がかかっていた。がしかし、
  - [ F0_L / accGND_L ] は 1/w/w がかかっていた。 
  - [ GND_L / accGND_L ]  も 1/w/w がかかっていた。
  - [ IP_LVDT_L / actIP_L ] はおかしくない。
- というわけで、モデルは合ってそう。
- modelが正しいとすると、LVDTで見ると(地面とIPの差動振動を読みとると、つまり [ (F0_L - GND_L) / accGND_L ] をみると)、(F0_L - GND_L)は、wが効く様子(modelでは)。

### todo for sanity check
- [ ] 上のcheck 用のplots を上げる。
- [ ] measure displacement TF [ IP_LVDT_L / GND_L ] and check if the simulated (issued) TF were strange indeed. (*1)
  - そんなもんかもね。[klog#7344](http://klog.icrr.u-tokyo.ac.jp/osl/?r=7344 "klog#7344") の (1,1) と (2,1) パネル。これは、地面の速度からIP_LVDTまでの振動伝達関数。
- [ ] hack the script to construct the ss-model to understand what was processed.
 
(*1) Tseki Dthesis のプロットは力変位伝達関数で、今回の問題は振動伝達なので、比べるべきがちょっと違う。IP自体の振動伝達は、高周波側でさちる(いわゆるCoP効果)やつ。地面との差動では、そういえば見たことない気がする。

**Comment by MiyoKouseki** [comment]
#### IP_LVDT_L/velGnd_L
[klog7344](http://klog.icrr.u-tokyo.ac.jp/osl/?r=7344)で計測したもの。
![image](https://user-images.githubusercontent.com/24282734/50069111-f502ad80-020b-11e9-880c-79c49bf94552.png)

#### IP_LVDT_L/accGnd_L
上記の測定とMiyo, Fuji, Etoalが計算したものとの関係は、

IP_LVDT_L / velGnd_L 
= IP_LVDT_L / ( accGnd_L * 1/s )
= ( IP_LVDT_L / accGnd_L ) * s 

s=iwなので、計算したものからさらに位相が更に90°進むことになる。けれどそれだと測定と-180°異なるが、これは、地震計かLVDTの+Lの定義が異なるから？ちょっと確かめる必要がありそうですね。

## Todo
- [ ] 地震計の符号と+Xアーム,+Yアームの符号を確かめる。
- [ ] IPのLVDT_Lの符号と+Xアーム,+Yアームの符号を確かめる。

**Comment by YoshinoriFujii** [comment]
> えっと、IP_LVDT_L/accGndLの結果は三代とetoalは同じで、これは測定とConsistentということでOK？

ですです。

>  IPのLVDT_Lの符号と+Xアーム,+Yアームの符号を確かめる。

ITMXのIP-LVDTの+L/+T方向と、+Xarm/+Yarm方向はコンシステントでした。
[gw-vis/ITMX#9](https://github.com/gw-vis/ITMX/issues/9 "gw-vis/ITMX#9")

というわけで、モデルと実測は合ってそう、でOK？
- [ ] 何を見てるのか考える
