### ISSUE TITLE
Need noise budget of the PR3 **with** correction

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/sensor-correction#6]
## Background
need simulation model (.slx) for the sensor correction & feed-forwarding.
need noise budget ***after*** implementing sensor correction on the BF LVDT in L/T.

## ToDo
- [ ] Prepare the model ".slx" including the sensor-correction (& feed-forwarding) part
- [ ] plot noise budget longitudinal displacement of the TM with correction,
- [ ] plot noise budget longitudinal velocity of the TM with correction,
- [ ] plot noise budget oplev pitch of the TM with correction,
- [ ] Done

## Note
- とりあえずsensor correctionだけやってみた場合を計算する? -> のち直観とコンシステントか確認
- feed-forwardingも含めたモデルを作っておく(.slx)
( - feed-forwardingも含めた場合の noise budgetは別にissueを立てる。)

**Comment by YoshinoriFujii** [comment]
## Need to design the filters

### todo
- [ ] design the filters for sensor correction and feed-forwarding
  - [ ] for SF-GAS
  - [ ] for BF-{L/T}

- [ ] filterを実装した後、どこを見るのが正解？を見積もっておく。
  - [ ] SF-GAS => BF-V?
  - [ ]

**Comment by YoshinoriFujii** [comment]
> design the filters for sensor correction and feed-forwarding
   for SF-GAS  

PR3-SFGAS-LVDT で 試してみた。引くことには引けた様子はあったけれど、さくっといけるだろうと考えていたら泥沼にはまったので、冷静になってから考え直すことにする。

### reference
https://www.evernote.com/l/AoPp5E1nNDNA-orxDfJeQf5wFRz8m2p7KEM/

**Comment by YoshinoriFujii** [comment]
以下に更新しました。
BF-L: https://www.evernote.com/l/AoO2BqPHqPFK54ozBdTkhRmEETY_-_pUDp0/
SF-GAS: https://www.evernote.com/l/AoN1vFeoRdBAAZ0BJ6C7EalR7WI0rHg-IeE/

- とりあえずはさっぴけた by implementing Hd * 1/H with appropriate low-pass or band-pass as the fed-forward filter F_ff.
  - Here, Hd is the displacement transfer function from GND to the appropriate sensor and H is the mechanical transfer function.

- For the next,
  - GND_X to BF_P, then IM_L のルートによる地面振動の鏡への伝達をカットしてみる。
    - 要PRs model変更。

**Comment by YoshinoriFujii** [comment]
~ May 21th 2019, 
- GND-L to BF-L, GND-T to BF-R
